version: '3.2'
services:
  metabase:
    image: metabase/metabase
  cypress:
    entrypoint: bash -c "sleep 90 && cypress run --spec /e2e/cypress/integration/metabase-api-test.js"
    image: "cypress/included:3.2.0"
    environment:
      - CYPRESS_baseUrl=http://metabase:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
