version: 2.1
orbs:
  cypress: cypress-io/cypress@1

executors:
  default:
    machine:

workflows:
  build:
    jobs:
      - cypress/run:
          executor: default
          start: docker run -p 3000:3000  metabase/metabase
          wait-on: 'http://localhost:3000'
