version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
 run-ui-tests:
   machine: true
   steps:
     - checkout
     - run: |
         script/run_ui_tests.sh


workflows:
  build:
    jobs:
      - run-ui-tests
