version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
 test:
   machine: true
   steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            wget -qO- https://deb.nodesource.com/setup_10.x | sudo -E bash && \
                apt-get install -y nodejs && \
                node -v && \
                npm install -g yarn
            npm install
            scripts/run_ui_tests.sh
workflows:
  default:
    jobs:
      - test
