version: 2.1

jobs:
 api-test:
   machine: true
   steps:
      - checkout
      - run:
          name: "Run api tests"
          command: |
            script/run_api_tests.sh
 ui-test:
   machine: true
   steps:
      - checkout
      - run:
          name: "Run ui tests"
          command: |
            script/run_ui_tests.sh
workflows:
  default:
    jobs:
      - api-test
      - ui-test
