version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
 api-test:
   machine:
     image: ubuntu-1604:201903-01
     resource_class: large
   steps:
      - checkout
      - run:
          name: "Run api tests"
          command: |
            script/run_api_tests.sh
 ui-test:
   machine: true
   steps:
      - checkout
      - run:
          name: "Run ui tests"
          command: |
            script/run_ui_tests.sh
workflows:
  default:
    jobs:
      - api-test
      - ui-test
