version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
 api-test:
   machine: true
   steps:
      - checkout
      - run:
          name: Install node@v8.11.3
          command: |
            ./load-nvm.sh
            nvm install v6.14.7
            nvm alias default v6.14.7
      - cypress/install
      - run:
          name: "Run api tests"
          command: |
            script/run_api_tests.sh
 ui-test:
   machine: true
   steps:
      - checkout
      - cypress/install
      - run:
          name: "Run ui tests"
          command: |
            script/run_ui_tests.sh
workflows:
  default:
    jobs:
      - api-test
      - ui-test
