version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
 test:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         npm install
         scripts/run_ui_tests.sh
workflows:
  default:
    jobs:
      - test
